<a href="https://colab.research.google.com/github/RahulJuluru2/Unit1ClassPractice/blob/main/B19votingExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier

In [ ]:
iris = load_iris()
X = iris.data[:,0:4]
y = iris.target

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
algos=[]
algos.append(('lr',LogisticRegression(max_iter=200)))
algos.append(('dt',DecisionTreeClassifier()))
algos.append(('sv',SVC(probability=True)))

In [ ]:
algos

[('lr', LogisticRegression(max_iter=200)),
 ('dt', DecisionTreeClassifier()),
 ('sv', SVC(probability=True))]

In [ ]:
x_train[:10,:]

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1]])

In [ ]:
vot_h = VotingClassifier(estimators=algos,voting="hard")
vot_h.fit(x_train,y_train)
ypredh = vot_h.predict(x_test)

In [ ]:
ypredhac = vot_h.predict([[4.6, 3.6, 1. , 0.2]])
ypredhac

array([0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_test,ypredh))

1.0


In [ ]:
vot_s = VotingClassifier(estimators=algos,voting="soft")
vot_s.fit(x_train,y_train)
ypreds = vot_s.predict(x_test)

In [ ]:
print(accuracy_score(y_test,ypreds))

1.0


In [ ]:
ypredsoft = vot_s.predict_proba([[4.6, 3.6, 1. , 0.2]])
ypredsoft

array([[0.99294445, 0.00436763, 0.00268792]])

In [ ]:
ypredac = vot_s.predict([[4.6, 3.6, 1. , 0.2]])

In [ ]:
ypredac

array([0])